# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7471040fa94eaac8ec0169a90e10eddf103a4f4a4bc959f8854034552cad38c5d5f518139ca7db48a6beefda89eb282bc4b3ce1ce9dbcf716229d98a2aacb418

test:
  secret_key_base: 7ff055bd5d0b164d02042c7ad78b45479dc8e754873f58e97cc40c589941a5b45f9d1559894d750dd96ff8f821fd9e228520f5e8bf7fa6224a5b784df147f066

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
