class CreateOpt10059s < ActiveRecord::Migration
  def change
    create_table :opt10059s, id:false ,:comment => "종목별투자자기관별요청종합" do |t|
      t.timestamp :stock_date ,:comment => "일자"
      t.string :stock_code, limit:9  ,:comment => "종목코드"
      t.integer :current_price ,:comment => "현재가"
      t.integer :contrast_symbol  ,:comment => "대비기호"
      t.integer :contrast_yesterday ,:comment => "전일대비"
      t.decimal :fluctuation_rate, precision:5, scale:2  ,:comment => "등락율"
      t.integer :accumulated_trade_price ,:comment => "누적거래대금"
      t.integer :net_buy_price_domestic_investor  ,:comment => "순매수_금액_개인투자자"
      t.integer :net_buy_amount_domestic_investor ,:comment => "순매수_거래량_개인투자자"
      t.integer :buy_price_domestic_investor ,:comment => "매수_금액_개인투자자"
      t.integer :buy_amount_domestic_investor ,:comment => "매수_거래량_개인투자자"
      t.integer :sell_price_domestic_investorr ,:comment => "매도_금액_개인투자자"
      t.integer :sell_amount_domestic_investor ,:comment => "매도_거래량_개인투자자"
      t.integer :net_buy_price_foreign_investor ,:comment => "순매수_금액_외국인투자자"
      t.integer :net_buy_amount_foreign_investor ,:comment => "순매수_거래량_외국인투자자"
      t.integer :buy_price_foreign_investor ,:comment => "매수_금액_외국인투자자"
      t.integer :buy_amount_foreign_investor ,:comment => "매수_거래량_외국인투자자"
      t.integer :sell_price_foreign_investor ,:comment => "매도_금액_외국인투자자"
      t.integer :sell_amount_foreign_investor ,:comment => "매도_거래량_외국인투자자"
      t.integer :net_buy_price_institution ,:comment => "순매수_금액_기관계"
      t.integer :net_buy_amount_institution ,:comment => "순매수_거래량_기관계"
      t.integer :buy_price_institution ,:comment => "매수_금액_기관계"
      t.integer :buy_amount_institution ,:comment => "매수_거래량_기관계"
      t.integer :sell_price_institution ,:comment => "매도_금액_기관계"
      t.integer :sell_amount_institution ,:comment => "매도_거래량_기관계"
      t.integer :net_buy_price_financial_investment ,:comment => "순매수_금액_금융투자"
      t.integer :net_buy_amount_financial_investment ,:comment => "순매수_거래량_금융투자"
      t.integer :buy_price_financial_investment ,:comment => "매수_금액_금융투자"
      t.integer :buy_amount_financial_investment ,:comment => "매수_거래량_금융투자"
      t.integer :sell_price_financial_investment ,:comment => "매도_금액_금융투자"
      t.integer :sell_amount_financial_investment ,:comment => "매도_거래량_금융투자"
      t.integer :net_buy_price_insurance  ,:comment => "순매수_금액_보험"
      t.integer :net_buy_amount_insurance  ,:comment => "순매수_거래량_보험"
      t.integer :buy_price_insurance  ,:comment => "매수_금액_보험"
      t.integer :buy_amount_insurance  ,:comment => "매수_거래량_보험"
      t.integer :sell_price_insurance  ,:comment => "매도_금액_보험"
      t.integer :sell_amount_insurance  ,:comment => "매도_거래량_보험"
      t.integer :net_buy_price_investment_trust ,:comment => "순매수_금액_투자신탁"
      t.integer :net_buy_amount_investment_trust ,:comment => "순매수_거래량_투자신탁"
      t.integer :buy_price_investment_trust ,:comment => "매수_금액_투자신탁"
      t.integer :buy_amount_investment_trust ,:comment => "매수_거래량_투자신탁"
      t.integer :sell_price_investment_trust ,:comment => "매도_금액_투자신탁"
      t.integer :sell_amount_investment_trust ,:comment => "매도_거래량_투자신탁"
      t.integer :net_buy_price_etc_financial ,:comment => "순매수_금액_기타금융"
      t.integer :net_buy_amount_etc_financial ,:comment => "순매수_거래량_기타금융"
      t.integer :buy_price_etc_financial ,:comment => "매수_금액_기타금융"
      t.integer :buy_amount_etc_financial ,:comment => "매수_거래량_기타금융"
      t.integer :sell_price_etc_financial ,:comment => "매도_금액_기타금융"
      t.integer :sell_amount_etc_financial ,:comment => "매도_거래량_기타금융"
      t.integer :net_buy_price_bank ,:comment => "순매수_금액_은행"
      t.integer :net_buy_amount_bank ,:comment => "순매수_거래량_은행"
      t.integer :buy_price_bank ,:comment => "매수_금액_은행"
      t.integer :buy_amount_bank ,:comment => "매수_거래량_은행"
      t.integer :sell_price_bank ,:comment => "매도_금액_은행"
      t.integer :sell_amount_bank ,:comment => "매도_거래량_은행"
      t.integer :net_buy_price_pension_fund ,:comment => "순매수_금액_연기금등"
      t.integer :net_buy_amount_pension_fund ,:comment => "순매수_거래량_연기금등"
      t.integer :buy_price_pension_fund ,:comment => "매수_금액_연기금등"
      t.integer :buy_amount_pension_fund ,:comment => "매수_거래량_연기금등"
      t.integer :sell_price_pension_fund ,:comment => "매도_금액_연기금등"
      t.integer :sell_amount_pension_fund ,:comment => "매도_거래량_연기금등"
      t.integer :net_buy_price_private_equity_fund ,:comment => "순매수_금액_사모펀드"
      t.integer :net_buy_amount_private_equity_fund ,:comment => "순매수_거래량_사모펀드"
      t.integer :buy_price_private_equity_fund ,:comment => "매수_금액_사모펀드"
      t.integer :buy_amount_private_equity_fund ,:comment => "매수_거래량_사모펀드"
      t.integer :sell_price_private_equity_fund ,:comment => "매도_금액_사모펀드"
      t.integer :sell_amount_private_equity_fund ,:comment => "매도_거래량_사모펀드"
      t.integer :net_buy_price_nation ,:comment => "순매수_금액_국가"
      t.integer :net_buy_amount_nation ,:comment => "순매수_거래량_국가"
      t.integer :buy_price_nation ,:comment => "매수_금액_국가"
      t.integer :buy_amount_nation ,:comment => "매수_거래량_국가"
      t.integer :sell_price_nation ,:comment => "매도_금액_국가"
      t.integer :sell_amount_nation ,:comment => "매도_거래량_국가"
      t.integer :net_buy_price_etc_corporation ,:comment => "순매수_금액_기타법인"
      t.integer :net_buy_amount_etc_corporation ,:comment => "순매수_거래량_기타법인"
      t.integer :buy_price_etc_corporation ,:comment => "매수_금액_기타법인"
      t.integer :buy_amount_etc_corporation ,:comment => "매수_거래량_기타법인"
      t.integer :sell_price_etc_corporation ,:comment => "매도_금액_기타법인"
      t.integer :sell_amount_etc_corporation ,:comment => "매도_거래량_기타법인"
      t.integer :net_buy_price_foregin_investment_in_korea ,:comment => "순매수_금액_내외국인"
      t.integer :net_buy_amount_foregin_investment_in_korea ,:comment => "순매수_거래량_내외국인"
      t.integer :buy_price_foregin_investment_in_korea ,:comment => "매수_금액_내외국인"
      t.integer :buy_amount_foregin_investment_in_korea ,:comment => "매수_거래량_내외국인"
      t.integer :sell_price_foregin_investment_in_korea ,:comment => "매도_금액_내외국인"
      t.integer :sell_amount_foregin_investment_in_korea ,:comment => "매도_거래량_내외국인"

      t.timestamps null: false
    end
    add_index :opt10059s, [:stock_date, :stock_code] , unique: true

  end
end
